apiVersion: v1
kind: Service
metadata:
  name: kube-world
  labels:
    app: kube-world
spec:
  selector:
    app: kube-world
  type: NodePort
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 9999