apiVersion: v1
kind: Service
metadata:
  name: kube-world
  labels:
    run: kube-world
spec:
  ports:
    - port: 8888
      targetPort: 9999
      protocol: TCP
  type: NodePort
  selector:
    run: kube-world